### ISSUE TITLE
Node Version? - TypeError: Cannot set property crypto of #<Object> which has only a getter

### ISSUE THREAD

**Issue by djekl** [liamcottle/meshtastic-bot#1]
What version of NodeJS are you using?

```bash
node index.js
file:///Users/FriendlyDev/meshtastic-projects/liamcottle/meshtastic-bot/index.js:10
globalThis.crypto = webcrypto;
                  ^

TypeError: Cannot set property crypto of #<Object> which has only a getter
    at file:///Users/FriendlyDev/meshtastic-projects/liamcottle/meshtastic-bot/index.js:10:19
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)

Node.js v20.11.0
```

To fix this issue, I added a function to set the `globalThis` value if it wasn't already set.

```nodejs
function setGlobalParam(key, value) {
    if ("undefined" === typeof globalThis[key]) {
        Object.defineProperty(globalThis, key, {
            value: value,
            enumerable: false,
            configurable: true,
            writable: true,
        });
    }
}
```

Then used it like this:
```nodejs
setGlobalParam('crypto', webcrypto);
setGlobalParam('navigator', {
    bluetooth: bluetooth,
});
```

I'm not a node or javascript developer, so I don't know if there is a better way to do this.

**Comment by liamcottle** [comment]
I'm on NodeJS `v18.12.1`, haven't tested on newer versions yet sorry.

Ideally, the `@meshtastic/js` package shouldn't rely on browser apis being available, but I believe it was developed with the intention of using on the web, and NodeJS support hasn't been added yet. No idea if it's planned.

The code throwing errors here, is because I'm patching out the global variables that the package expects to exist, but I guess NodeJS v20+ does something different with global variables.

I will need to look into this further for the best fix, but haven't had a chance to upgrade Node versions on my machine yet.

**Comment by djekl** [comment]
Thanks for the reply Liam. Yeah going from web code to Node isn't always easy. Especially when you bring in things like ES6 and CommonJS.

The fix provided works btw, so good to reference if you get this error.
